version: '2'
services:
  unit-tests-demo:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: cvc/unit-tests-demo
    ports:
      - "8080:8080"
    environment:
      - CONSUL_HOST=consul-local
      - CONSUL_PORT=8500
      - VAULT_HOST=vault-local
      - VAULT_SCHEME=http
      - VAULT_SECURITY_TOKEN=myroot
      - ADDITIONAL_OPTS= -Dspring.profiles.active=local
    links:
      - consul-local
      - vault-local
    depends_on:
      - consul-local
      - vault-local
  consul-local:
    image: consul:1.1.0
    ports:
      - 8500:8500
  consul-cli:
    image: consul:1.1.0
    ports:
      - "8500"
    environment:
      - CONSUL_HTTP_ADDR=http://consul-local:8500
    volumes:
      - "./data/consul:/tmp/consul-seed"
    command: consul kv import @/tmp/consul-seed/data.json
    links:
      - consul-local
    depends_on:
      - consul-local
  vault-local:
    image: vault:0.8.3
    ports:
      - 8200:8200
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
    cap_add:
      - IPC_LOCK
  vault-ui:
    image: djenriquez/vault-ui
    ports:
      - "8000:8000"
    links:
      - vault-local
    depends_on:
      - vault-local
    environment:
      VAULT_URL_DEFAULT: http://vault-local:8200
      VAULT_AUTH_DEFAULT: TOKEN
  vault-cli:
    image: vault:0.8.3
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_TOKEN=myroot
      - VAULT_ADDR=http://vault-local:8200
    command: vault write secret/unit-tests-demo spring.datasource.password=sa spring.datasource.username=sa
    depends_on:
      - vault-local
    links:
      - vault-local

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.2.0/24
          gateway: 172.21.2.1